### ISSUE TITLE
DD_ENV doesn't get set from env parameter

### ISSUE THREAD

**Issue by cscetbon** [DataDog/datadog-cloudformation-macro#92]
## Expected Behavior

DD_ENV should be set from env parameter

## Actual Behavior

DD_ENV is not set and no tags are added as well to the lambdas

Steps to Reproduce the Problem

`sam init`
`template.yaml` content:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
- Name: DatadogServerless
   Parameters:
     pythonLayerVersion: 72
      stackName: datadog-serverless-macro
      service: my-service
      env: !Ref StageName

Parameters:
  StageName:
    Type: String
    Default: dev

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
```

My `src/app.py` contains a simple dummy handler(not relevant)
```
def lambda_handler(event, context):
    print('Hello')
```

Specifications for the Datadog Serverless Macro:

```
Deployment method and version (CloudFormation, SAM, CDK): sam 1.80.0
Datadog CloudFormation Macro version: 72
Lambda function runtime (Python 3.7, Node 10, etc.): python3.8
```

```
$ sam build
Building codeuri: /Users/cscetbon/Downloads/test/src runtime: python3.8 metadata: {} architecture: x86_64 functions: MyFunction
requirements.txt file not found. Continuing the build without dependencies.
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
```

```
$ aws lambda get-function --function-name xxxxx-MyFunction-xxxx
{
            "FunctionName": "xxxxx-MyFunction-xxxx",
            ...
            "Runtime": "python3.8",
            "Handler": "datadog_lambda.handler.handler",
            "CodeSize": 615780,
            "Description": "",
            "Timeout": 900,
            "MemorySize": 1024,
            "LastModified": "2023-05-12T13:59:08.000+0000",
            "CodeSha256": "rBS5z16SwlMo+i6VAn7BV6dM3Z1bBHv54n1zzcQhBSE=",
            "Version": "$LATEST",
...
            },
            "Environment": {
                "Variables": {
                    "DD_LAMBDA_HANDLER": "handler.handler",
                    "DD_CAPTURE_LAMBDA_PAYLOAD": "false",
                    "DD_FLUSH_TO_LOG": "true",
                    "DD_TRACE_ENABLED": "true",
                    "ENV_NAME": "stg",
                    "DD_SERVERLESS_LOGS_ENABLED": "true",
                    "DD_ENHANCED_METRICS": "true",
                    "DD_MERGE_XRAY_TRACES": "false"
                }
...
"Tags": {
...
        "dd_sls_macro_by": "SAM",
        "dd_sls_macro": "v0.5.2",
...
    }
}
```

You can see that DD_ENV is missing
